export const SUBJECT_FETCH = 'SUBJECT_FETCH';
export const SUBJECT_RECEIVE = 'SUBJECT_RECEIVE';
export const UNIT_FETCH = 'UNIT_FETCH';
export const UNIT_RECEIVE = 'UNIT_RECEIVE';

export const CONTENT_FETCH = 'CONTENT_FETCH';
export const CONTENT_RECEIVE = 'CONTENT_RECEIVE';
export const DOCUMENT_COMMENT_SEND = 'DOCUMENT_COMMENT_SEND';
export const DOCUMENT_COMMENT_RECEIVE = 'DOCUMENT_COMMENT_RECEIVE';

export const AUTH_LOGIN_FETCH = 'AUTH_LOGIN_FETCH';
export const AUTH_LOGIN_RECEIVE = 'AUTH_LOGIN_RECEIVE';
export const AUTH_USERDATA_FETCH = 'AUTH_USERDATA_FETCH';
export const AUTH_USERDATA_RECEIVE = 'AUTH_USERDATA_RECEIVE';
export const AUTH_USERDATA_FAILED = 'AUTH_USERDATA_FAILED';

export const EXERCISE_FETCH = 'EXERCISE_FETCH';
export const EXERCISE_RECEIVE = 'EXERCISE_RECEIVE';
export const EXERCISE_COMMENT_SEND = 'EXERCISE_COMMENT_SEND';
export const EXERCISE_COMMENT_RECEIVE = 'EXERCISE_COMMENT_RECEIVE';

export const GUIDE_FETCH = 'GUIDE_FETCH';
export const GUIDE_RECEIVE = 'GUIDE_RECEIVE';
export const GUIDE_SEND = 'GUIDE_SEND';
